### PR TITLE
Updated steps for the journey

### PR DESCRIPTION
**Pull request by easternbloc**
*** The removal of backlinks in this PR is dependant on a change that I'm going to PR in hmpo-form-wizard ***

If the user now selects any option that skips reasons they are directed to a new page (personal-details-no-reason)

This page has the same controller as personal-details but fixes the issue of the backlink going to /reason

Added more comprehensive tests to cover these use cases.

*Update*

Added extra fields to emails as per email requirements

### CODE REVIEW

**Comment by easternbloc** [comment]
Gonna add the remainder of the someone-else code in here then re-open.

**Comment by JoeChapman** [comment]
@easternbloc 
Step 2: No error message when reason is not described

**Comment by easternbloc** [comment]
:angry:

**Comment by easternbloc** [comment]
@JoeChapman done

**Pull request merged**
