### PR TITLE
Update copy for nationality field

### PR DESCRIPTION
**Pull request by easternbloc**

### CODE REVIEW

**Comment by vaijab** [comment]
LGTM

**Comment by easternbloc** [comment]
@vaijab I think as @JoeChapman is away you can merge or I'm just gonna self merge...

**Comment by vaijab** [comment]
> or I'm just gonna self merge...

I am happy to quickly `LGTM` it and you can then merge it yourself.

**Comment by easternbloc** [comment]
Sounds good to me.

**Pull request merged**
