### PR TITLE
Update the response copy in the collection email

### PR DESCRIPTION
**Pull request by easternbloc**
This adds a message informing users about the closure of oxford street post office.

### CODE REVIEW

**Comment by joefitter** [comment]
apart from build failing dependency checks - LGTM

**Comment by easternbloc** [comment]
@joefitter i've removed that for now. It was just a test to see how it interacted with our workflow. Can you merge to brp?

**Comment by joefitter** [comment]
👍  and no, i don't haz teh permissionz

**Comment by easternbloc** [comment]
@joefitter thanks. I've added you as a mergererererer now.

**Comment by joefitter** [comment]
manythanksyouverymuch

**Pull request merged**
