### PR TITLE
Ensure we clear the session at the end of every journey

### PR DESCRIPTION
**Pull request by easternbloc**

### CODE REVIEW

**Comment by vaijab** [comment]
What happens when there is no session to clear? Say the session does not exist in the session store?

**Comment by JoeChapman** [comment]
@vaijab do you mean, what happens in the code?
If there is no session, it fails gracefully with no error.

**Comment by easternbloc** [comment]
@vaijab @JoeChapman the same code runs at the start page of each journey to ensure the session is clear. This is just a measure so the user can't hit back and submit an email again. Instead they are redirected to the start page...

**Comment by vaijab** [comment]
@easternbloc understood. Thanks.

**Pull request merged**
